alias flutter_pkgs_get='flutter pub get'
alias flutter_pkgs_upgrade='flutter packages pub upgrade'
alias flutter_doctor='flutter doctor -v'
alias flutter_run='flutter run'
alias flutter_clean='flutter clean'
alias flutter_scanfoold='flutter create --sample=material.Scaffold.2 mysample'